source_name: "Street Cameras"
source_type: "video"
source_mode: "rtsp_video"
source_list:
  - name: "street_camera_0"
    url: ""
    dir: "street_0_h264"
    metadata:
      resolution: "1080p"
      fps: 30
      encoding: "mp4v"
      buffer_size: 4


